version: '3.6'

services:

  pnpm:
    build:
      context: .
      dockerfile: .docker/DockerFile
    volumes:
      - .:/app:rw,cached
    working_dir: /app
    environment:
      - USER_ID=${UID:-1001}
    ports:
      - 3100:3000
    command: ["npm", "run", "dev"]
    networks:
      - sylius

networks:
  sylius:
    external: true